cmake_minimum_required(VERSION 3.28.0)

list(
    APPEND 
    EXTRA_CONF_FILE
        ${CMAKE_CURRENT_SOURCE_DIR}/embedded-pio/zephyrcan/zephyrcan.conf
        ${CMAKE_CURRENT_SOURCE_DIR}/embedded-pio/zephyrethernet/zephyrethernet.conf
)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(canExample)

add_subdirectory(embedded-pio/zephyrcan)
add_subdirectory(embedded-pio/zephyrethernet)

target_include_directories(app 
    PRIVATE 
        inc
)

target_sources(app 
    PRIVATE 
        src/main.cpp
        src/examplecan.cpp
        inc/examplecan.h
        inc/const.h
)

target_link_libraries(app
    PRIVATE
        zephyrcan
        zephyrethernet
)
